Feature/search
plecto/django-smart-lists pull request #2
Opened 2017-03-16 15:37 UTC by Maxtaager

generic search please review @KristianOellegaard

2017-03-16 16:01 UTC, KristianOellegaard requested changes
Hey Mikkel,

Please take a look at these changes and then I think we can merge it in.

Thank you very much for the work so far on this!

2017-03-16 16:01 UTC, KristianOellegaard commented on smart_lists/helpers.py
> +        self.search_term = list_settings.get('search_term')
This should be consistently named with ```self.ordering_query_param``` - I suggest ```self.search_query_param```

2017-03-16 16:01 UTC, KristianOellegaard commented on smart_lists/mixins.py
> +        qs = self.get_search_results(qs)
Use similar code style as filters and ordering

```
search = self.get_search()
if search:
    qs = qs.filter(**search)
```

2017-03-16 16:01 UTC, KristianOellegaard commented on smart_lists/mixins.py
> +        def construct_search(field_name):
Don't define functions inside class methods

2017-03-16 16:01 UTC, KristianOellegaard commented on smart_lists/mixins.py
> +            if field_name.startswith('^'):
Re-implement search lookup names similar to django admin, not use strange looking characters that might have weird URL encodings.

Query should look like this:
```?q=asd```

Variables should look like this:
```search_fields = ('company_name', 'code')```

2017-03-17 08:49 UTC, Maxtaager commented on smart_lists/mixins.py
> +            if field_name.startswith('^'):
i did take it from django-admin django/contrib/admin/options.py class ModelAdmin method get_search_result.
A crazy idea would be to call this method directly... (but that might break across django versions).
def get_search_results(self, request, queryset, search_term):

or i could rewrite the code using a more simple lookup with only contains, that would make the code much cleaner.

2017-03-17 08:57 UTC, Maxtaager commented on smart_lists/mixins.py
> +            if field_name.startswith('^'):
renamed search parameter to q=? instead of search=?

2017-03-29 14:09 UTC, KristianOellegaard commented on smart_lists/mixins.py
> +            if field_name.startswith('^'):
LGTM

2017-03-29 14:40 UTC, closed without merging